apiVersion: v1
kind: Service
metadata:
  name: census-demography
  namespace: census
  labels:
    app: census-demography
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: census-demography